P403n1x87/echion

echion/bootstrap/__init__.py
echion/coremodule.cc

We make sure that tracking happens after a module that needs patching is imported.

chore: fix tracking logic for patched modules

---

echion/coremodule.cc
echion/threads.h

Acquiring the CPU clock ID requires a pthread_t, which might become unavaiable if the ID is being retrieved with every update. Since the tracking happens with the GIL, that is the best time to grab the clock ID and store it for future use.

fix(linux): acquire CPU clock ID on thread tracking

---

echion/cpython/tasks.h
echion/frame.h
echion/strings.h

Fixed a memory leak when retrieving byte arrays (line number tables) that were never deallocated after use. We move to automatic memory management with smart pointers to allow for the clean up to happen.

fix: memory leak in Python bytes object retrieval

---

echion/threads.h

Ensure that we actually have the origin in the origin map before attempting to dereference it. Since we do not hold the task link map lock for longer than we need, the trade-off for performance is a potential loss os sync with the data collected in earlier stages of the unwind_tasks method. Therefore we do not make the assumption that the lookup is always successful to prevent potential invalid memory dereferencing.

fix: task link origin lookup

---

echion/cpython/tasks.h
echion/mirrors.h

When allocating memory using a size value read from copied memory, we make sure that the value is sensible before attempting the allocation.

fix: guard allocation size

---

echion/frame.h
echion/threads.h

The lifetime of some global variables is managed manually. Automatic management done on exit can race with the one done manually, causing issues such as double free.

fix: manage global variables lifetime

---

echion/coremodule.cc
echion/frame.h
echion/stacks.h
echion/strings.h
echion/tasks.h
echion/threads.h

We introduce a string table to centralise the handling of strings used for frame information. This is an intermediate step to get to implementing support for the MOJO binary format for data compression.

chore: introduce a string table

---

echion/interp.h

chore: remove unused init in interpreter unwinding

---

echion/coremodule.cc

With recent refactors, a signal handler installation call was left out in the original place. This is now redundant and can be removed to clean up the coding.

chore: remove duplicate signal handler setup

---

echion/coremodule.cc

We update the thread tracking data structure by replacing the existing thread info object with a new one to ensure full proper initialisation and proper tracking data.

chore: proper thread tracking update

---

echion/__main__.py
tests/test_echion.py

We allow passing in interval units, such as ms and s, as a way to abbreviate large microsecond intervals (e.g. 10ms instead of 10000).

feat: handle interval units

---

echion/monkey/threading.py

We make sure that threads get untracked under any circumstances, including when the target raises an exception.

fix: ensure threads are always untracked

---

echion/long.h
echion/strings.h

`pylong_to_llong()` is a helper function to extract task id for CPython versions 3.12+

Add `pylong_to_llong()`

---

echion/config.h
echion/frame.h
echion/signals.h
echion/stacks.h
echion/strings.h
setup.py

When `UNWIND_NATIVE_DISABLE` is set, libunwind and liblzma is not needed to compile echion.

Add preprocessor checks for UNWIND_NATIVE_DISABLE

---

.github/workflows/tests.yml
echion/vm.h

In many configurations, `process_vm_readv()` may be blocked at the syscall level (e.g., common Docker seccomp profile). This provides a simple failover using `writev()`. Note that this mechanism is not faster than `process_vm_readv()`.
This PR adds a few things.
- (semi-related) adds a quick failover in the common case of zero-page access
- Adds a check at static initialization on Linux for the availability of `process_vm_readv()`
- Implements a `VmReader` singleton class which holds the state for using alternative methods for reading VM. I could have put the `process_vm_readv()` switch here instead, but in the moment it felt right to factor this orthogonally to the current implementation
- Adds an environment variable, `ECHION_ALT_VM_READ_FORCE` for forcing the alternative safe reader …

Add a `safe_copy()` alternative for linux using `writev()`

---

echion/threads.h

We make sure we don't accidentally mistaken a native thread for the main thread when we don't find its native ID within the thread tracking map. This can happen when attaching to a running process using hypno, in which case we are likely to be missing the main thread. There are cases where we can still get into the logic that supports this case, but for native threads that are not the main thread. When these threads die, they won't untrack themselves, causing us to look up their clock ID on Linux and crash.

fix: track main thread only if missing

---

echion/threads.h

#83 introduced a check that a `PyThreadState` is skipped sampling if there's already `MainThread` in the `thread id` to `ThreadInfo` map. That unintentionally resulted in not traversing the `prev` and `next` `PyThreadState`s from the skipped one. This PR fixes that behavior.

fix: traverse `prev` and `next` tstates even if current one is skipped

---

echion/frame.h

Noticed while running dd-trace-py with ddprof, using 1.95s out of 7.32s (26%) of stack_v2 cpu time
This change drastically reduces the amount of time we spend on `process_vm_readv`

fix: copy code object only when cache miss

---

echion/frame.h
echion/stack_chunk.h
echion/stacks.h

#74 enabled us to read from local `stack_chunk` when available. And some of CPython 3.13+ tests were segfaulting since then, see #85 for examples. This PR fixes them. 
Since CPython 3.13, objects other than code objects can exist as "executable" of an internal frame, see 	https://github.com/python/cpython/pull/105727. This required us to iterate over frame objects checking the type, and we need to make sure those frame addresses are resolved using `stack_chunk` or copied properly.

fix: CPython 3.13+ resolves frame addresses using stack_chunk

---

echion/cache.h
echion/config.h
echion/frame.cc
echion/frame.h
echion/memory.h
echion/mojo.h
echion/signals.h
echion/stack_chunk.h
echion/stacks.h
echion/state.h
echion/strings.h
echion/tasks.h
echion/threads.h
echion/timing.h
echion/vm.h
setup.py

- Splits `frame.h` into header and `.cc` files to avoid circular dependency between `render.h` and `frame.h` as in #67, this also resulted in some cascading changes in other headers to update their `#include`s
- Use `inline` instead of `static` for global variables, as now we have multiple `.cc` files including those headers. Using `static` leads to having own copies of such variables in those `.cc` files.

refactor: split frame.h into frame.h and frame.cc

---

echion/config.h
echion/frame.cc

ddtrace has 
- `-Werror=shadow`
- `-Werror=old-style-cast`
- `-Werror=non-virtual-dtor`
fixes errors from these here.

refactor: fix compile errors when used from ddtrace

---

echion/frame.cc

refactor: fix compile errors when used from ddtrace with 3.13

---

echion/stack_chunk.h
echion/stacks.h

This PR saves roughly 160ms per minute from stack v2 on a customer provided test environment, by avoiding frequent memory allocations/frees for `StackChunk`. 
SxS comparison
`StackChunk` holds data stack from the profiled Python thread. It basically is a linked list of temporary buffers (`char[]`). Echion used to allocate and free whole data structure for every thread for every sampling interval. This PR instead reallocates the buffers when more space is needed and avoid such behavior.
One caveat is that the amount of memory that we use for `StackChunk` could increase over time, if program being profiled somehow results in deeper and deeper Python stack traces over time. 
Before 
After
Another thing to note is that it drastically reduces
- number of allocations (5724 -> 355)
- amount of …

perf: re-use stackchunk buffer as much as possible

---

echion/stacks.h

`ThreadInfo::unwind_tasks()` calls `task.unwind(*stack)` to unwind the frames from a task, which calls into `unwind_frame()` in `stacks.h` 
`unwind_frame()` increments `count` variable whenever it sees a frame that hasn't been seen, and then tries to create a `Frame` object and push it into `stack` variable. However, if it fails to create the `Frame` object, the function would return `count` which is greater than the number of `Frame` objects in the `stack`. 
Then, `ThreadInfo::unwind_tasks()` calls `pop_back()` on the `stack` for `count` number of times. This could lead to an undefined behavior and crash if `unwind_frame()` has returned a number larger than the actual number of elements in the `stack`.

fix: increment count only when frame was successfully created and pushed

---

echion/stack_chunk.h

Accidentally removed this line in #102 
Then, why didn't we notice stack_chunk was not used in SxS comparison on #102? The answer is in #105

fix: set origin pointer to make stackchunk useful again

---

.github/workflows/tests.yml
echion/bootstrap/__init__.py
echion/config.h
echion/coremodule.cc
echion/vm.h

This PR changes a few things
1. Adds a new sigtrap VM reader mode
2. Changes the semantics, interface, and naming of the VM reader override
3. Propagates those changes to the bootstrap init and the tests
Broadly speaking, here's what the sigtrap handler does
1. Sets up a signal handler for both SIGBUS and SIGSEGV (bad addressing can raise either)
2. Whenever a memory read is about to happen, register the read.  Currently assumes single-threaded operation, which is consistent with the echion sampling strategy
3. If the signal trap doesn't fire--great!  This is the typical case
4. If the signal trap fires *and* the fault is within the request pre-registered with the system, resume execution and pass `false` to the vmreader infrastructure
5. if the signal trap fires, but the fault is outside …

use a sigtrap-based memory reader

---

echion/frame.cc
echion/mirrors.h

Noticed that 3.11 showed too many `process_vm_readv` calls, coming from `Frame::read`, which should have been resolved using `stack_chunk` for most cases. See the red box in below image. 
While implementing stack chunk logic for 3.13 in #88, this wasn't properly addressed. So this is reclaiming what was initially introduced by #74 and accidentally removed by #88. 
All tests passed on (https://github.com/DataDog/dd-trace-py/pull/13230)

fix: 3.11 and 3.12 uses datastack chunk for frame address resolution

---

echion/threads.h

We fix a bug whereby CPU time would be accounted for all the tasks running on the CPU-bound thread. When sampling in CPU mode, we only collect the task that has an active coroutine only. This way we account for just the actual work currently on CPU.

fix: proper asyncio CPU time accounting

---

echion/frame.cc
echion/mojo.h
echion/render.h

We make the bitmask for mojo references larger to avoid potential reference collisions when parsing the generated data.

fix: use larger mojo reference key

---

tests/target_mem.py
tests/test_memory.py

We speed up the memory test by reducing the number of allocations.

tests: make memory test faster

---

echion/strings.h

We make the string table thread-safe by locking when calling its read/write methods.

chore: make string table thread-safe

---

echion/greenlets.h
echion/render.h
echion/stacks.h
echion/tasks.h
echion/threads.h

We refactor the task stack collection logic to include task metadata, such as the leaf task name and the on-CPU status. This information can then be passed on to the renderer to make more informed decisions on how to handle the collected stacks.

refactor: retain task metadata

---

echion/render.h
echion/threads.h

Ensure that we honour a request to sample non-running tasks when also computing CPU time

fix: honour ignore_non_running_threads

---

echion/threads.h

If we comment out `unwind_frame()` function body except for `int count = 0; and return count;` and run
```
echion --cpu -o profiles/task.mojo ~/.pyenv/versions/3.13.3/bin/python3.13 -m tests.target_gather
```
with `target_gather.py` from https://gist.github.com/taegyunkim/df3ddc68731668b7d2fe33e44632037a
We get the following stack traceback from coredump 
```
#2  0x00007b884363a9a6 in std::deque<std::reference_wrapper<Frame>, std::allocator<std::reference_wrapper<Frame> > >::push_back (this=0x7b883c0087f0, __x=...) at /usr/include/c++/11/bits/stl_deque.h:1501
#3  0x00007b884362d235 in ThreadInfo::unwind_tasks (this=0x63d29b0bc790) at ./echion/threads.h:303
#4  0x00007b884362c75c in ThreadInfo::unwind (this=0x63d29b0bc790, tstate=0x7b884305fe50) at ./echion/threads.h:170
No locals.
#5 …
```

Avoids UB on `python_stack` by using unsigned types with underflow check

---

echion/stack_chunk.h

When `StackChunk` is constructed, it doesn't initialize the backing `data` and `data_capacity` is 0. 
It's initialized only when `if (chunk.size > data_capacity)` holds, but then if `chunk.size` is 0 too for some reason, we avoid allocating memory for `data` and we could in theory can get null pointer there. 
Maybe this could happen when the `_PyStackChunk` is being initialized and has not yet updated its `size` field. 
So we'd need to allocate some memory when `data.get()` is a nullptr

fix: check for null chunk ptr

---

echion/strings.h

This PR removes an unneeded `try` / `catch` block from the code. It's a functional no-op and I don't expect it to have any positive impact on performance.
I checked and as far as I know/can tell:
- The buffer stack allocation cannot throw
- `std::snprintf` cannot throw
- `this->emplace` may (maybe? I don't know) throw but definitely not a `StringError`, so the current `catch` wouldn't catch it 
- `Renderer::get()` and `Renderer::string` cannot throw a `StringError`
I suspect this was added to replicate what was done in `inline Key key(PyObject* s)` but this one actually needs it in case `pyunicode_to_utf8` throws.

fix: remove unneeded try/catch

---

echion/coremodule.cc
echion/greenlets.h
echion/memory.h
echion/mojo.h
echion/render.h
echion/signals.h
echion/stacks.h
echion/tasks.h
echion/threads.h
echion/vm.h

This PR 
- Marks all relevant function/method definitions as `inline` to avoid getting warnings about potential ODR violations
- Defining symbols (functions/methods but also variables) in header files can be problematic if a header file is included in more than a single translation unit, as it would lead to symbols being defined more than once and fail linking
- In echion, we only have on `.cc` file, so this isn't a problem in practice
- However, this gives me warnings as it could in theory be a problem
- Marking those definitions as `inline` tells the compiler to trust us, and makes it so that the linker will merge definitions as long as they are identical.
- Removes unused `#include`'s

misc: mark function defs as `inline` for odr
